DoanMVC/Controllers/AboutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;

namespace DoanMVC.Controllers
{
    public class AboutsController : Controller
    {
        // GET: Abouts
        public ActionResult About()
        {
            return View();
        }
        public ActionResult gioithieu()
        {
            var item = new AboutDao().about(1);
            return PartialView();
        }
    }
}

DoanMVC/Controllers/ProducController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using PagedList;
using System.Runtime.InteropServices;


namespace DoanMVC.Controllers
{
    public class ProducController : Controller
    {
        // GET: Produc
        public ActionResult Product()
        {
            return View();
        }

        [HttpGet]
        public JsonResult LoadDataAll(int page, int pageSize, string sort = "")
        {
            var model = new ProductDao().ListAll(sort);
            int totalRow = model.Count();
            model = model.Skip((page - 1) * pageSize).Take(pageSize);

            return Json(new
            {
                data = model,
                total = totalRow,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
        [ChildActionOnly]
        public ActionResult ProductMenu()
        {
            var model = new MenuDao().ListByGroupId(3);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult ProductHot()
        {
            var model = new ProductDao().TopHot(5);
            return PartialView(model);
        }

        [OutputCache(CacheProfile = "Cache1DayForProduct")]
        public ActionResult Detail(long id)
        {
            var product = new ProductDao().ViewDetail(id);
            ViewBag.Category = new CategoryDao().ViewDetail(product.ID);
            ViewBag.RelatedProduct = new ProductDao().ListRelatedProduct(id);
            new ProductDao().InsertView(id);
            new ProductDao().InsertLike(id);
            return View(product);
        }
        public ActionResult Category(long id)
        {
            var category = new CategoryDao().ViewDetail(id);
            ViewBag.Category = category;
            //var model = new ProductDao().ListByCategoryId(id);
            return View(/*model*/);
        }
        public ActionResult ProductBanChay()
        {
            return View();
        }
        [HttpGet]
        public JsonResult LoadDataAllBest(int page, int pageSize, string sort = "")
        {
            var model = new ProductDao().AllBuyBestProduct(sort);
            int totalRow = model.Count();
            model = model.Skip((page - 1) * pageSize).Take(pageSize);

            return Json(new
            {
                data = model,
                total = totalRow,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ProductMoi()
        {
            return View();
        }
        [HttpGet]
        public JsonResult LoadDataAllMoi(int page, int pageSize, string sort = "")
        {
            var model = new ProductDao().ProductMoi(sort);
            int totalRow = model.Count();
            model = model.Skip((page - 1) * pageSize).Take(pageSize);

            return Json(new
            {
                data = model,
                total = totalRow,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ProductView()
        {
            return View();
        }
        [HttpGet]
        public JsonResult LoadDataAllView(int page, int pageSize, string sort = "")
        {
            var model = new ProductDao().ProductView(sort);
            int totalRow = model.Count();
            model = model.Skip((page - 1) * pageSize).Take(pageSize);

            return Json(new
            {
                data = model,
                total = totalRow,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ProductSale()
        {                
            return View();
        }
        [HttpGet]
        public JsonResult LoadDataAllSale(int page, int pageSize, string sort = "")
        {
            var model = new ProductDao().ProductSale(sort);
            int totalRow = model.Count();
            model = model.Skip((page - 1) * pageSize).Take(pageSize);

            return Json(new
            {
                data = model,
                total = totalRow,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Search(string keyword, int page = 1, int pageSize = 1)
        {
            int totalRecord = 0;
            var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }
    }
}

DoanMVC/Views/Abouts/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var item = (IEnumerable<Model.EF.ABOUT>)ViewBag.GioiThieu;
}

<main class="wrapper main-content" role="main">

    <!-- /snippets/breadcrumb.liquid -->

    <nav class="breadcrumb" role="navigation" aria-label="breadcrumbs">
        <img src='../../hstatic.net/033/1000104033/1000147703/bg-breadcrumb8f26.jpg?v=55' alt='' />
        <div class="inner">
            <div class="breadcrumb-list">
                <a href="../index.html" title="Quay lại trang chủ">Trang chủ</a>

                <span aria-hidden="true">/</span>
                <span>Giới thiệu</span>

            </div>

            <h3 class="page_name">Giới thiệu</h3>

        </div>
    </nav>

    <!-- /templates/page.liquid -->

    <div class="grid">
        <div class="sidebar grid__item large--one-quarter">
            <div class="collection-sidebar">
                <!-- /snippets/collection-sidebar.liquid -->
                @{ Html.RenderAction("ProductMenu", "Produc");}

               @{Html.RenderAction("ProductHot", "Produc"); }

                <div class="widget-cms widget">

                    <h4 class="widget__title">CMS Hướng dẫn</h4>

                    <em>khối CMS tùy chỉnh hiển thị ở thanh bên trái trên Catalog trang. Đặt nội dung của riêng bạn ở đây:. Text, html, hình ảnh, truyền thông ... bất cứ điều gì bạn thích </ em> <br> <em> Có rất nhiều tương tự như giữ chỗ nội dung mẫu trên cửa hàng. Tất cả có thể chỉnh sửa từ bảng quản trị.</em>
                </div><!-- end advertising -->
            </div>

        </div>
        <div class="grid__item large--three-quarters ">

            <div class="rte">
                <p>Trang giới thiệu giúp khách hàng hiểu rõ hơn về cửa hàng của bạn. Hãy cung cấp thông tin cụ thể về việc kinh doanh, về cửa hàng, thông tin liên hệ. Điều này sẽ giúp khách hàng cảm thấy tin tưởng khi mua hàng trên website của bạn.</p><p>Một vài gợi ý cho nội dung trang Giới thiệu:</p><div><ul><li><span>Bạn là ai</span><br></li><li><span>Giá trị kinh doanh của bạn là gì</span><br></li><li><span>Địa chỉ cửa hàng</span><br></li><li><span>Bạn đã kinh doanh trong ngành hàng này bao lâu rồi</span><br></li><li><span>Bạn kinh doanh ngành hàng online được bao lâu</span><br></li><li><span>Đội ngũ của bạn gồm những ai</span><br></li><li><span>Thông tin liên hệ</span><br></li><li><span>Liên kết đến các trang mạng xã hội (Twitter, Facebook)</span><br></li></ul></div>
            </div>

        </div>

    </div>


</main>