DoanMVC/Areas/Admin/Controllers/BaseController.cs
using DoanMVC.Common;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace DoanMVC.Areas.Admin.Controllers
{
    public class BaseController : Controller
    {
        //initilizing culture on controller initialization
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            if (Session[CommonConstants.CurrentCulture] != null)
            {
                Thread.CurrentThread.CurrentCulture = new CultureInfo(Session[CommonConstants.CurrentCulture].ToString());
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(Session[CommonConstants.CurrentCulture].ToString());
            }
            else
            {
                Session[CommonConstants.CurrentCulture] = "vi";
                Thread.CurrentThread.CurrentCulture = new CultureInfo("vi");
                Thread.CurrentThread.CurrentUICulture = new CultureInfo("vi");
            }
        }

        // changing culture
        public ActionResult ChangeCulture(string ddlCulture, string returnUrl)
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(ddlCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(ddlCulture);

            Session[CommonConstants.CurrentCulture] = ddlCulture;
            return Redirect(returnUrl);
        }
        // kiêm tra đã đang nhập admin
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var session = (UserLogin)Session[CommonConstants.USER_SESSION];
            if (session == null)
            {
                filterContext.Result = new RedirectToRouteResult(new
                    RouteValueDictionary(new { controller = "Login", action = "Index", Area = "Admin" }));
            }
            base.OnActionExecuting(filterContext);
        }
        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            if (type == "success")
            {
                TempData["AlertType"] = "alert-success";
            }
            else if (type == "warning")
            {
                TempData["AlertType"] = "alert-warning";
            }
            else if (type == "error")
            {
                TempData["AlertType"] = "alert-danger";
            }
        }
    }
}

DoanMVC/Areas/Admin/Views/Shared/401.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}
@section header{
    Lỗi không có quyền truy cập 

}
<div class="alert alert-danger">
    Bạn không có quyền truy cập.
</div>

DoanMVC/Areas/Admin/Views/Shared/_LayoutAD.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Đồ dùng học tập T&Q</title>
    <!-- Bootstrap Core CSS -->
    <link href="/Content/admin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/Content/admin/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/Content/admin/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/Content/admin/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        @RenderPage("_Navigation.cshtml")
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">@RenderSection("header",required: true)</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                @if (TempData["AlertMessage"] != null)
                {
                    <div id="AlertBox" class="alert @TempData["AlertType"] hide">
                        @TempData["AlertMessage"]
                    </div>
                }

                @RenderBody()
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="/Content/admin/vendor/jquery/jquery.min.js"></script>
    <script src="/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Content/admin/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/Content/admin/dist/js/sb-admin-2.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->  
    <script src="/Content/admin/vendor/metisMenu/metisMenu.min.js"></script>
    <script src="/Content/admin/js/Plugins/ckfinder/ckfinder.js"></script>
    <script src="/Content/admin/js/Plugins/ckeditor/ckeditor.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/Content/admin/dist/js/sb-admin-2.js"></script>
    @RenderSection("jsFooter",required:false)
</body>
</html>

DoanMVC/Areas/Admin/Views/Shared/_Navigation.cshtml
@{
    var session = (DoanMVC.Common.UserLogin)Session[DoanMVC.Common.CommonConstants.USER_SESSION];
}
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/Admin/Home/Index"><i class="fa fa-anchor" aria-hidden="true"></i>Trang Chủ Quản Trị Viên</a>
    </div>
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">

        <li>
            @using (Html.BeginForm("ChangeCulture", "Base"))
            {
                @Html.Hidden("returnUrl", Request.RawUrl)
                @Html.DropDownList("ddlCulture", new SelectList(new[] {
                    new {value="vi",text=StaticResources.Resources.Vietnamese},
                    new {value="en",text=StaticResources.Resources.English},

                    }, "value", "text", Session[DoanMVC.Common.CommonConstants.CurrentCulture]), new { onchange = "this.form.submit();" })
            }
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href=""><i class="fa fa-user fa-fw"></i>@session.UserName</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/Admin/Login/Logout"><i class="fa fa-sign-out fa-fw"></i> Thoát</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search.">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </li>
                <li>
                    <a href="/Admin/Home/Index"><i class="fa fa-dashboard fa-fw"></i> Trang chủ</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-user fa-fw"></i> Hệ thống<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="/Admin/UserGroup/Index">Nhóm người dùng</a>
                        </li>
                        <li>
                            <a href="/Admin/User/Index">User</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-comment fa-fw"></i> Tin tức<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="/Admin/Category/Index">Danh mục</a>
                        </li>
                        <li>
                            <a href="/Admin/Content/Index">Tin tức</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>

                <li>
                    <a href="/Admin/Product/Index"><i class="fa fa-bell fa-fw"></i> Sản phẩm<span class="fa arrow"></span></a>
                </li>
                <li>
                    <a href="/Admin/Order/Index"><i class="fa fa-certificate"></i> Hóa đơn <span class="fa arrow"></span></a>
                </li>

                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Quản lý chung<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="/Admin/Logo/Index">Logo</a>
                        </li>
                        <li>
                            <a href="/Admin/Slide/Index">Slide</a>
                        </li>
                        <li>
                            <a href="/Admin/Feedback/Index">Phản hồi</a>
                        </li>
                        <li>
                            <a href="/Admin/Contact/Index">Liên hệ</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
</nav>