DoanMVC/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoanMVC.Models;
using Model.DAO;
using System.Web.Script.Serialization;
using Model.EF;
using System.Configuration;
using Common;
using DoanMVC.Common;

namespace DoanMVC.Controllers
{
    public class CartsController : Controller
    {
        private const string CartSession = "CartSession";
        // GET: Carts
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        [HttpPost]
        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.Product.ID == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        [HttpPost]
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];

            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.ID == item.Product.ID);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        public ActionResult AddItem(long productId)
        {
            var product = new ProductDao().ViewDetail(productId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.Product.ID == productId))
                {

                    foreach (var item in list)
                    {
                        if (item.Product.ID == productId)
                        {
                            item.Quantity += 1;
                        }
                    }
                }
                else
                {
                    //tạo mới đối tượng cart item
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = 1;
                    list.Add(item);
                }
                //Gán vào session
                Session[CartSession] = list;
            }
            else
            {
                //tạo mới đối tượng cart item
                var item = new CartItem();
                item.Product = product;
                item.Quantity = 1;
                var list = new List<CartItem>();
                list.Add(item);
                //Gán vào session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult Cart()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return PartialView(list);
        }

        [ChildActionOnly]
        public ActionResult InFoCart()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return PartialView(list);
        }
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }
        [HttpPost]
        public ActionResult Payment(string shipName, string mobile, string address, string email)
        {
            var order = new ORDER();
            order.CretedDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipMobile = mobile;
            order.ShipName = shipName;
            order.ShipEmail = email;

            try
            {
                var id = new OrderDao().Insert(order);
                var cart = (List<CartItem>)Session[CartSession];
                var detailDao = new Model.DAO.OrderDetailDao();
                decimal total = 0;
                foreach (var item in cart)
                {
                    var orderDetail = new ORDERDETAIL();
                    orderDetail.ProductID = item.Product.ID;
                    orderDetail.OrderID = id;
                    orderDetail.Price = item.Product.Price;
                    orderDetail.Quantity = item.Quantity;
                    detailDao.Insert(orderDetail);

                    total += (item.Product.Price.GetValueOrDefault(0) * item.Quantity);
                }
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Areas/Client/template/neworder.html"));

                content = content.Replace("{{CustomerName}}", shipName);
                content = content.Replace("{{Phone}}", mobile);
                content = content.Replace("{{Email}}", email);
                content = content.Replace("{{Address}}", address);
                content = content.Replace("{{Total}}", total.ToString("N0"));
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                new MailHelper().SendMail(email, "Đơn hàng mới từ Basic", content);
                new MailHelper().SendMail(toEmail, "Đơn hàng mới từ Basic", content);
            }
            catch (Exception)
            {
                //ghi log
                return Redirect("/loi-thanh-toan.html");
            }
            return Redirect("/hoan-thanh.html");
        }

        public ActionResult Success()
        {
            return View();
        }

        public JsonResult GetUser()
        {
            var model = (AccountLogin)Session[CommonConstants.AccountSession];
            if (model == null)
            {
                return Json(new
                {
                    status = false
                });
            }
            return Json(new
            {
                data = model,
                status = true
            });
        }
        [HttpPost]
        public JsonResult CreateOrder(string orderViewModel)
        {
            var order = new JavaScriptSerializer().Deserialize<OrderViewModel>(orderViewModel);
            var orderDao = new OrderDao();
            var orderNew = new ORDER();
            orderNew.CretedDate = DateTime.Now;
            orderNew.ShipAddress = order.CustomerAddress;
            orderNew.ShipMobile = order.CustomerMobile;
            orderNew.ShipName = order.CustomerName;
            orderNew.ShipEmail = order.CustomerEmail;
            orderNew.CustomerMessage = order.CustomerMessage;
            orderNew.PaymentMethod = order.PaymentMethod;
            orderNew.PaymentStatus = order.PaymentStatus;
            orderNew.Status = true;
            orderDao.Insert(orderNew);
            var detailDao = new OrderDetailDao();
            var sessionCart = (List<CartItem>)Session[CommonConstants.CartSession];
            decimal total = 0;
            foreach (var item in sessionCart)
            {
                var detail = new ORDERDETAIL();
                detail.OrderID = orderNew.ID;
                detail.ProductID = item.Product.ID;
                detail.Quantity = item.Quantity;
                if (item.Product.PromotionPrice.HasValue)
                {
                    detail.Price = item.Product.PromotionPrice.Value;
                    total += (item.Product.PromotionPrice.GetValueOrDefault(0) * item.Quantity);
                }
                else
                {
                    detail.Price = item.Product.Price;
                    total += (item.Product.Price.Value * item.Quantity);
                }
                detailDao.Insert(detail);
            }

            string content = System.IO.File.ReadAllText(Server.MapPath("~/Areas/Client/template/neworder.html"));
            content = content.Replace("{{CustomerName}}", order.CustomerName);
            content = content.Replace("{{Phone}}", order.CustomerMobile);
            content = content.Replace("{{Email}}", order.CustomerEmail);
            content = content.Replace("{{Address}}", order.CustomerAddress);
            content = content.Replace("{{Total}}", total.ToString("N0"));
            new MailHelper().SendMail(order.CustomerEmail, "Thông tin đơn đặt hàng từ T&Q", content);
            Session[CommonConstants.CartSession] = null;
            return Json(new
            {
                status = true
            });
        }
    }
}

DoanMVC/Controllers/TrangChuController.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoanMVC.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        public ActionResult Index()
        {
            var ProductDao = new ProductDao();
            ViewBag.Logos = new LogoDao().ListAll();
            ViewBag.ContentNew = new ContentDao().newContent(2);
            return View();
        }
        [ChildActionOnly]
        //[OutputCache(Duration = 3600 * 24)]
        public ActionResult MainMenu()
        {
            var model = new MenuDao().ListByGroupId(1);
            return PartialView(model);
        }
        [ChildActionOnly]
        //[OutputCache(Duration = 3600 * 24)]
        public ActionResult TopMenu()
        {
            var model = new MenuDao().ListByGroupId(2);
            return PartialView(model);
        }
        [ChildActionOnly]
        [OutputCache(Duration = 3600 * 24)]
        public ActionResult Footer()
        {
            var model = new FooterDao().GetFooter();
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult ProductHot()
        {
            var model = new ProductDao().TopHot(8);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult ProductNew()
        {
            var model = new ProductDao().NewProduct(8);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult ProductBest()
        {
            var model = new ProductDao().BuyBestProduct(8);
            return PartialView(model);
        }
        [ChildActionOnly]
        public ActionResult MainSlides()
        {
            var model = new SlidesDao().ListByGroupId(1);
            return PartialView(model);
        }
        [ChildActionOnly]
        public ActionResult BotSlides()
        {
            var model = new SlidesDao().ListByGroupId(2);
            return PartialView(model);
        }
    }
}

DoanMVC/Views/Shared/Footer.cshtml
@model Model.EF.FOOTER
@Html.Raw(Model.Content)

DoanMVC/Views/Shared/MainMenu.cshtml
@model List<Model.EF.MENU>
<div class="medium-down--hide">
    <!-- begin site-nav -->
    <ul class="site-nav" id="AccessibleNav">
        @foreach (var item in Model)
        {
            <li class="site-nav--active">
               <h4> <a href="@item.Link" target="@item.Target">@item.Text </a></h4>
            </li>
        }
       
    </ul>
    <!-- //site-nav -->
</div>

DoanMVC/Views/Shared/TopMenu.cshtml
@model List<Model.EF.MENU>
<div class="site-header__account ultility-item large--left">
    <span>
        Tài khoản
        <span class="fa fa-angle-down" aria-hidden="true"></span>
    </span>
    @{
        var session = (DoanMVC.Common.UserLogin)Session[DoanMVC.Common.CommonConstants.USER_SESSION];
    }
    @if (session == null)
    {
        <ul>
            @foreach (var item in Model)
            {
                <li>
                    <i class="fa fa-smile-o"></i>
                    <a href="@item.Link" class="customer_login_link" target="@item.Target">@item.Text</a>
                </li>
            }

        </ul>
    }
    else
    {
        <ul>
            <li> Xin chào: @session.UserName</li>
            <li> @Html.ActionLink("Thoát", "Logout", "Account")</li>
        </ul>
    }


</div>

DoanMVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js">
<head>

    <!-- Basic page needs ================================================== -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Title and description ================================================== -->
    <title>
        basic
    </title>
    <!-- Helpers ================================================== -->
    <!-- /snippets/social-meta-tags.liquid -->


    <meta property="og:type" content="website">
    <meta property="og:title" content="basic">

    <meta property="og:image" content="../hstatic.net/033/1000104033/1000147703/logo8f26.png?v=55">
    <meta property="og:image:secure_url" content="../hstatic.net/033/1000104033/1000147703/logo8f26.png?v=55">
    <meta property="og:url" content="index.html">
    <meta property="og:site_name" content="basic">
    <meta name="twitter:card" content="summary">


    <link rel="canonical" href="index.html">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="theme-color" content="#141414">
    <!-- font -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,600,700,500' rel='stylesheet' type='text/css'>
    <!-- CSS ================================================== -->
    <link href='/hstatic.net/033/1000104033/1000147703/bootstrap.min8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href="/Areas/Client/css/jquery-ui.css" rel="stylesheet" />

    <link href='/hstatic.net/033/1000104033/1000147703/font-awesome8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/elements8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/timber.scss8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/style.scss8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/owl.carousel8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/owl.theme8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/owl.transitions8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/animate8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />
    <link href='/hstatic.net/033/1000104033/1000147703/linearicons8f26.css?v=55' rel='stylesheet' type='text/css' media='all' />

    <!-- Header hook for plugins ================================================== -->
    <script type='text/javascript'>
        //<![CDATA[
        if ((typeof Haravan) === 'undefined') {
            Haravan = {};
        }
        Haravan.culture = 'vi-VN';
        Haravan.shop = 'basic.myharavan.com';
        Haravan.theme = { "name": "Basic", "id": 1000147703, "role": "main" };
        Haravan.domain = 'basic.myharavan.com';
        //]]>
    </script>


    <script src='/ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js' type='text/javascript'></script>
    <script src="/Areas/Client/js/jquery-1.11.3.min.js"></script>
    <script src="/Areas/Client/js/jquery-ui.js"></script>

    <script src='/hstatic.net/0/0/global/api.jquery.js' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/modernizr.min8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/bootstrap-custom8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/plugins.min8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/0/0/global/option_selection.js' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/jquery.jcarousellite8f26.js?v=55' type='text/javascript'></script>
</head>
<body id="basic" class="template-index">
    <div id="CartDrawer" class="drawer drawer--right">
        <div class="overlay"></div>
        <div class="drawer--popup-container">
            <div class="drawer__header">
                <div class="drawer__title h3">Giỏ hàng</div>
                <div class="drawer__close js-drawer-close">
                    <button type="button" class="icon-fallback-text">
                        <span class="icon icon-x" aria-hidden="true"></span>
                        <span class="fallback-text">"Đóng Giỏ hàng"</span>
                    </button>
                </div>
            </div>
            <div id="CartContainer">
                @{Html.RenderAction("InFoCart", "Carts");}
            </div>
        </div>
    </div>
    <div id="PageContainer" class="is-moved-by-drawer">
        <header class="site-header">
            <div class="wrapper">
                <!-- /snippets/header.liquid -->
                <div class="header">

                    <div class="site-header__topbar medium-down--hide">


                        @{ Html.RenderAction("TopMenu", "TrangChu"); }
                        <!-- end account -->
                        <div class="large--right">
                            <a href="cart.html" class="site-header__cart-toggle js-drawer-open-right" aria-controls="CartDrawer" aria-expanded="false">
                                @{Html.RenderAction("Cart", "Carts");}
                            </a>
                        </div><!--  end cart -->
                        <div class="site-header__search large--right">
                            <!-- /snippets/search-bar.liquid -->


                            <form action="/tim-kiem.html" method="get" class="input-group search-bar" role="search">

                                <input type="search" id="txtKeyword" name="keyword" value="" placeholder="Nhập vào tìm kiếm" class="input-group-field" aria-label="Nhập vào tìm kiếm">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn icon-fallback-text">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                        <span class="fallback-text">Tìm kiếm</span>
                                    </button>
                                </span>
                            </form>

                        </div> <!-- end search -->

                    </div>
                    <div class="logo">

                        <h1 class="site-header__logo" itemscope itemtype="http://schema.org/Organization">


                            <a href=@Url.Action("Index", "TrangChu") itemprop="url" class="site-header__logo-link">
                                <img src="../hstatic.net/033/1000104033/1000147703/logo8f26.png?v=55" alt="basic" itemprop="logo">
                            </a>


                        </h1>

                    </div>
                    <nav class="nav-bar keep-this" role="navigation">
                        <!-- /snippets/menu.liquid -->
                        @{Html.RenderAction("MainMenu", "TrangChu");}
                    </nav>

                </div>
            </div>
        </header> <!-- end header -->
        @RenderBody()

        <!-- begin site-footer -->
        @{Html.RenderAction("Footer", "TrangChu");}
 
        <!-- //site-footer -->
    </div>
    <script src='/hstatic.net/033/1000104033/1000147703/fastclick.min8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/timber8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/owl.carousel.min8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/wow.min8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/handlebars.min8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/ajax-cart8f26.js?v=55' type='text/javascript'></script>
    <script src="/services/javascripts/currencies.js" type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/jquery.currencies.min8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/quickview8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/wish-list8f26.js?v=55' type='text/javascript'></script>
    <script src='/hstatic.net/033/1000104033/1000147703/collection8f26.js?v=55' type='text/javascript'></script>
    <script src="~/Areas/Client/js/plugins/jquery.validate.js"></script>
    <script src="~/Areas/Client/js/plugins/additional-methods.js"></script>
    <script src="~/Areas/Client/js/plugins/mustache.min.js"></script>
    <script src="~/Areas/Client/js/plugins/numeral.js"></script>
    <script src="~/Areas/Client/js/plugins/jquery.twbsPagination.min.js"></script>

    <script src="/Areas/Client/js/Controllers/baseController.js"></script>
    @RenderSection("jsFooter", required: false)
    <!--Start of Zopim Live Chat Script-->
</body>

<!-- Mirrored from basic.myharavan.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 17 Sep 2016 06:08:43 GMT -->
</html>

DoanMVC/Views/Shared/_LayoutPM.cshtml
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="shortcut icon" href="hstatic.net/033/1000104033/1000147703/faviconcc31.png?v=801" type="image/png">
    <title>
        Basic - Thanh toán đơn hàng
    </title>
    <meta name="description" content="Basic - Thanh toán đơn hàng">
    <link href="/Areas/Client/css/check_out.css" rel="stylesheet" />
    <script src="/Areas/Client/js/jquery-1.9.1.mincc31.js" type='text/javascript'></script>
    <script src="/hstatic.net/033/1000104033/1000147703/jquery.validate.js"></script>
    <script src="/Areas/Client/js/additional-methods.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no">
</head>
<body class="step1">
    @RenderBody()
    @RenderSection("footerJS", required: false)
</body>
</html>